sudo: false # run on docker infrastructure

rvm:
  - 2.6.9
  - 2.7.5
  - 3.0.3

env:
  - "RAILS_VERSION=6.0"
  - "RAILS_VERSION=6.1"
  - "RAILS_VERSION=7.0"

matrix:
 exclude:
   - rvm: 2.7.5
     env: "RAILS_VERSION=7.0"
